"""Add employee table and link salaries

Revision ID: 23c1d61e48bb
Revises: 4b9e1e09d0a6
Create Date: 2026-01-12 15:25:33.356816

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23c1d61e48bb"
down_revision = "4b9e1e09d0a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_salaries', schema=None) as batch_op:batch_op.alter_column(
        "salary_source",
        existing_type=sa.TEXT(),
        type_=sa.String(length=20),
        existing_nullable=True,
        existing_server_default=sa.text("'TSC'"),
    )
    batch_op.drop_constraint(None, type_="foreignkey")
    batch_op.create_foreign_key(None, "employees", ["staff_id"], ["id"])
    batch_op.drop_column("extra_lessons")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("staff_salaries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "extra_lessons", sa.FLOAT(), server_default=sa.text("0"), nullable=True
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["staff_id"], ["id"])
        batch_op.alter_column(
            "salary_source",
            existing_type=sa.String(length=20),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("'TSC'"),
        )

    # ### end Alembic commands ###
