"""Add status column to staff_salaries

Revision ID: 4b9e1e09d0a6
Revises: 6165610d4738
Create Date: 2026-01-10 09:50:30.989642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9e1e09d0a6'
down_revision = '6165610d4738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_salaries', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
